# Generated by Django 3.2.14 on 2022-07-20 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20220720_0226'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='chat',
            name='receptor',
        ),
    ]
